/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AppDarkModeToggle: typeof import('./src/components/Application/AppDarkModeToggle.vue')['default']
    AppLogo: typeof import('./src/components/Application/AppLogo.vue')['default']
    AppProvider: typeof import('./src/components/Application/AppProvider.vue')['default']
    Bar: typeof import('./src/components/Scrollbar/src/Bar.vue')['default']
    BasicForm: typeof import('./src/components/Form/src/BasicForm.vue')['default']
    BasicHelp: typeof import('./src/components/Basic/BasicHelp.vue')['default']
    BasicModal: typeof import('./src/components/Modal/src/BasicModal.vue')['default']
    BasicTitle: typeof import('./src/components/Basic/BasicTitle.vue')['default']
    CountButton: typeof import('./src/components/Countdown/src/CountButton.vue')['default']
    CountDown: typeof import('./src/components/Countdown/src/CountDown.vue')['default']
    CountdownInput: typeof import('./src/components/Countdown/src/CountdownInput.vue')['default']
    FormItem: typeof import('./src/components/Form/src/components/FormItem.vue')['default']
    Icon: typeof import('./src/components/Icon/Icon.vue')['default']
    Loading: typeof import('./src/components/Loading/src/Loading.vue')['default']
    ModalClose: typeof import('./src/components/Modal/src/components/ModalClose.vue')['default']
    ModalFooter: typeof import('./src/components/Modal/src/components/ModalFooter.vue')['default']
    ModalHeader: typeof import('./src/components/Modal/src/components/ModalHeader.vue')['default']
    ModalWrapper: typeof import('./src/components/Modal/src/components/ModalWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scrollbar: typeof import('./src/components/Scrollbar/src/Scrollbar.vue')['default']
    Thumb: typeof import('./src/components/Scrollbar/src/Thumb.vue')['default']
  }
}

// For TSX support
declare global {
  const AButton: typeof import('ant-design-vue/es')['Button']
  const AppDarkModeToggle: typeof import('./src/components/Application/AppDarkModeToggle.vue')['default']
  const AppLogo: typeof import('./src/components/Application/AppLogo.vue')['default']
  const AppProvider: typeof import('./src/components/Application/AppProvider.vue')['default']
  const Bar: typeof import('./src/components/Scrollbar/src/Bar.vue')['default']
  const BasicForm: typeof import('./src/components/Form/src/BasicForm.vue')['default']
  const BasicHelp: typeof import('./src/components/Basic/BasicHelp.vue')['default']
  const BasicModal: typeof import('./src/components/Modal/src/BasicModal.vue')['default']
  const BasicTitle: typeof import('./src/components/Basic/BasicTitle.vue')['default']
  const CountButton: typeof import('./src/components/Countdown/src/CountButton.vue')['default']
  const CountDown: typeof import('./src/components/Countdown/src/CountDown.vue')['default']
  const CountdownInput: typeof import('./src/components/Countdown/src/CountdownInput.vue')['default']
  const FormItem: typeof import('./src/components/Form/src/components/FormItem.vue')['default']
  const Icon: typeof import('./src/components/Icon/Icon.vue')['default']
  const Loading: typeof import('./src/components/Loading/src/Loading.vue')['default']
  const ModalClose: typeof import('./src/components/Modal/src/components/ModalClose.vue')['default']
  const ModalFooter: typeof import('./src/components/Modal/src/components/ModalFooter.vue')['default']
  const ModalHeader: typeof import('./src/components/Modal/src/components/ModalHeader.vue')['default']
  const ModalWrapper: typeof import('./src/components/Modal/src/components/ModalWrapper.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Scrollbar: typeof import('./src/components/Scrollbar/src/Scrollbar.vue')['default']
  const Thumb: typeof import('./src/components/Scrollbar/src/Thumb.vue')['default']
}