/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDarkModeToggle: typeof import('./src/components/Application/AppDarkModeToggle.vue')['default']
    AppLogo: typeof import('./src/components/Application/AppLogo.vue')['default']
    AppProvider: typeof import('./src/components/Application/AppProvider.vue')['default']
    Bar: typeof import('./src/components/Scrollbar/src/Bar.vue')['default']
    BasicForm: typeof import('./src/components/Form/src/BasicForm.vue')['default']
    BasicHelp: typeof import('./src/components/Basic/BasicHelp.vue')['default']
    BasicModal: typeof import('./src/components/Modal/src/BasicModal.vue')['default']
    BasicTitle: typeof import('./src/components/Basic/BasicTitle.vue')['default']
    CountButton: typeof import('./src/components/Countdown/src/CountButton.vue')['default']
    CountDown: typeof import('./src/components/Countdown/src/CountDown.vue')['default']
    CountdownInput: typeof import('./src/components/Countdown/src/CountdownInput.vue')['default']
    FormItem: typeof import('./src/components/Form/src/components/FormItem.vue')['default']
    Icon: typeof import('./src/components/Icon/Icon.vue')['default']
    Loading: typeof import('./src/components/Loading/src/Loading.vue')['default']
    ModalClose: typeof import('./src/components/Modal/src/components/ModalClose.vue')['default']
    ModalFooter: typeof import('./src/components/Modal/src/components/ModalFooter.vue')['default']
    ModalHeader: typeof import('./src/components/Modal/src/components/ModalHeader.vue')['default']
    ModalWrapper: typeof import('./src/components/Modal/src/components/ModalWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scrollbar: typeof import('./src/components/Scrollbar/src/Scrollbar.vue')['default']
    Thumb: typeof import('./src/components/Scrollbar/src/Thumb.vue')['default']
  }
}
