/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/components/Application/AppLogo.vue')['default']
    AppProvider: typeof import('./src/components/Application/AppProvider.vue')['default']
    BasicHelp: typeof import('./src/components/Basic/BasicHelp.vue')['default']
    BasicModal: typeof import('./src/components/Modal/BasicModal.vue')['default']
    BasicTitle: typeof import('./src/components/Basic/BasicTitle.vue')['default']
    Icon: typeof import('./src/components/Icon/Icon.vue')['default']
    Loading: typeof import('./src/components/Loading/src/Loading.vue')['default']
    ModalClose: typeof import('./src/components/Modal/components/ModalClose.vue')['default']
    ModalHeader: typeof import('./src/components/Modal/components/ModalHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
