export const APP_DARK_MODE_KEY = "__APP__DARK__MODE__"
export const PROJ_CFG_KEY = "PROJ__CFG__KEY__"
export const TOKEN_KEY = "TOKEN__"
export const USER_INFO_KEY = "USER__INFO__"
export const ROLES_KEY = "ROLES__KEY__"
export const MULTIPLE_TABS_KEY = "MULTIPLE_TABS__KEY__"
export const TABLE_SETTING_KEY = "TABLE__SETTING__KEY__"